name: CI test to build SCM

on: [push, pull_request]

jobs:
  build-linux:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fortran-compiler: [gfortran]
    env:
      NFHOME: /home/runner/netcdf-fortran
      BCHOME: /home/runner/bacio
      SPHOME: /home/runner/NCEPLIBS-sp
      WCHOME: /home/runner/myw3emc
      LD_LIBRARY_PATH: /home/runner/netcdf-fortran/lib
      BUILD_TYPE: Release
      BUILD_DIR: _build
      CMAKE_OPTIONS: >-
        -DCMAKE_BUILD_TYPE=Debug

    steps:

    ###############################################################################
    # Setup
    ###############################################################################

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Initialize submodules
      run: git submodule update --init --recursive
    
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v3
      with:
        python-version: 3.8.5

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install f90nml
      run: conda install --yes -c conda-forge f90nml

    - name: Set compiler
      run: |
        echo "FC=gfortran-9" >> $GITHUB_ENV
        echo "CC=gcc-9" >> $GITHUB_ENV

    - name: Install bacio library
      run: |
        git clone https://github.com/NOAA-EMC/NCEPLIBS-bacio.git bacio
        cd bacio && mkdir build && cd build
        cmake ../ -DCMAKE_INSTALL_PREFIX=${BCHOME}
        make -j2
        make install
        echo "bacio_DIR=/home/runner/bacio/lib/cmake/bacio" >> $GITHUB_ENV

    - name: Install SPlib
      run: |
        git clone https://github.com/NOAA-EMC/NCEPLIBS-sp.git NCEPLIBS-sp
        cd NCEPLIBS-sp && mkdir build && cd build
        cmake -DCMAKE_INSTALL_PREFIX=${SPHOME} ../
        make -j2
        make install
        echo "sp_DIR=/home/runner/NCEPLIBS-sp/lib/cmake/sp" >> $GITHUB_ENV

    - name: Install w3emc
      run: |
        git clone https://github.com/NOAA-EMC/NCEPLIBS-w3emc.git NCEPLIBS-w3emc
        cd NCEPLIBS-w3emc && mkdir build && cd build
        cmake -DCMAKE_INSTALL_PREFIX=${WCHOME} ../
        make -j2
        make install
        echo "w3emc_DIR=/home/runner/myw3emc/lib/cmake/w3emc" >> $GITHUB_ENV

    - name: Install NetCDF C library
      run: sudo apt-get install libnetcdf-dev

    - name: Install NetCDF Fortran library
      run: |
        git clone https://github.com/Unidata/netcdf-fortran.git --branch v4.4.4
        cd netcdf-fortran
        ./configure
        make -j
        sudo make install

    - name: Add NETCDF to LD_LIBRARY_PATH
      run: |
        export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${NFHOME}/lib
        export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${BCHOME}/lib
        export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${SPHOME}/lib
        export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${WCHOME}/lib

    ###############################################################################
    #
    ###############################################################################
    - name: Install cmake
      run: pip3 install cmake ninja fypp

    - name: Configure build
      run: |
        cd /home/runner/work/ccpp-scm/ccpp-scm/scm/src
        cmake ../src
#        cmake -B ${BUILD_DIR} -G Ninja
#        -DCMAKE_INSTALL_PREFIX=${PWD}/_install
#        ${CMAKE_OPTIONS}
