name: CI test to build SCM

on: [push, pull_request]

jobs:
  build-linux:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fortran-compiler: [gfortran]
    env:
      NFHOME: /home/runner/netcdf-fortran
      LD_LIBRARY_PATH: /home/runner/netcdf-fortran/lib
      DYLD_LIBRARY_PATH: /home/runner/netcdf-fortran/lib
      CC: gcc
      CXX: g++
      FC: gfortran
      CMAKE_C_COMPILER: gcc
      CMAKE_CXX_COMPILER: g++
      CMAKE_Fortran_COMPILER: gfortran
      CMAKE_Platform: ubuntu-latest.gnu

    steps:

    ###############################################################################
    # Setup
    ###############################################################################

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Initialize submodules
      run: git submodule update --init --recursive
    
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v3
      with:
        python-version: 3.8.5

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install f90nml
      run: conda install --yes -c conda-forge f90nml

    - name: Install gfortran
      run: conda install --yes -c conda-forge ${{ matrix.fortran-compiler }}

    - name: Install netcdf
      run: conda install --yes -c conda-forge libnetcdf

    - name: Install cmake
      run: conda install --yes -c anaconda cmake

    - name: Add NETCDF to LD_LIBRARY_PATH
      run: export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${NFHOME}/lib

    - name: Add NETCDF to DYLD_LIBRARY_PATH
      run: export DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH}:${NFHOME}/lib

    ###############################################################################
    #
    ###############################################################################

    - name: Run CMake
      run: |
        pwd
        echo ${{github.workspace}}
        mkdir -p ${{github.workspace}}/scm/bin
        cd ${{github.workspace}}/scm/src
        cmake ${{github.workspace}}/scm/src
