name: CI checks for CCPP-SCM

on: [push, pull_request]

jobs:
  build:

    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:

    # A) Checks-out repository under $GITHUB_WORKSPACE
    - name: Checkout code
      uses: actions/checkout@v2
    
    # B) Set up Python and install dependencies
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    # C) Set up Conda and install dependencies
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        python-version: 3.7
    - name: Install python packages
      run: conda install --yes cartopy matplotlib netcdf4

    # D) CCPP_prebuild.py
    - name: Run ccpp_prebuild.py
      run: |
        ./ccpp/framework/scripts/ccpp_prebuild.py --config ccpp/config/ccpp_prebuild_config.py --builddir=./scm/bin
