name: CI checks for CCPP-SCM

on: [push, pull_request]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    ###############################################################################
    # Initial steps
    ###############################################################################
    # Set up Python and install dependencies
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        python-version: 3.7
    - name: Install python packages
      run: conda install --yes cartopy matplotlib netcdf4
    # Update system packages
    - name: Update system packages
      run: sudo apt-get update
    # Non compiler-specific environment
    - name: Non compiler-specific environment
      run: export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${NFHOME}/lib

    - name: Run ccpp_prebuild.py
      run: |
        source /opt/intel/oneapi/setvars.sh || true
        ./ccpp/framework/scripts/ccpp_prebuild.py --config ccpp/config/ccpp_prebuild_config.py --builddir=./scm/bin
